version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  heroku: circleci/heroku@1.2.3

executors:
  default:
    working_directory: ~/search-word-app
    docker:
      - image: circleci/ruby:2.7
        environment:
          APP_DATABASE_HOST: "127.0.0.1"
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

commands:
  bundle-install:
    steps:
      - ruby-orbs/bundle-install:
          bundle_clean: true
          bundle_extra_args: ''
          bundle_gemfile: Gemfile
          bundle_jobs: 3
          bundle_path: vendor/bundle
          bundle_retry: 3
          cache_key_prefix: v1-bundle-dependencies
          restore_bundled_with: true

jobs:
  build:
    executor: default
    steps:
      - checkout
      - bundle-install

  test:
    executor: default
    docker:
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: pass
    steps:
      - checkout
      - bundle-install
      - run:
          name: Database setup
          command: bundle exec rails db:create && db:migrate
      - run:
          name: test
          command: bundle exec rails test

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build