version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.5.7
    working_directory: ~/search-word-app
    steps:
      - checkout
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:2.5.7
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: pass
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/search-word-app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:create && db:migrate
      - run:
          name: test
          command: bundle exec rails test

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build