version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@2.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.5.7
      
    working_directory: ~/search-word-app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y build-essential nodejs default-mysql-client default-libmysqlclient-dev vim
      - ruby/install-deps

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.5.7
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: pass
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/search-word-app
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:create && db:migrate
      - run:
          name: test
          command: bundle exec rails test

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build